### ISSUE TITLE
request for pre-trained models for 256*256 resolution

### ISSUE THREAD

**Issue by LeeeLiu** [samuelmat19/GLOW-tf2#3]
Could you please share your pre-trained models for 256*256 resolution?
very much thanks.

**Comment by samkoesnadi** [comment]
I haven't trained it on 256*256 resolution because I do not have the computational resource to do so quickly. However, if you will do it, please contribute and share us the model

**Comment by LeeeLiu** [comment]
Got it. thank you all the same




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 晚上11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [samuelmat19/GLOW-tf2] request for pre-trained models for 256*256 resolution (#3)





 
I haven't trained it on 256*256 resolution because I do not have the computational resource to do so quickly. However, if you will do it, please contribute and share us the model
